# Streamlit secrets for My Medi.AI chatbot

OPENAI_API_KEY = "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"