GOOGLE_MAPS_API_KEY = "AIzaSyAV9wl5LyeXTXx1AelqgiFpgGtsRI1q4b8"
OPENAI_API_KEY = "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"
